import fs from 'node:fs/promises';

const checked = '2026-07-18';
const base = (name, role, org, group, sub, city, linkedin, event, activity, relevance, contribution, doors, ease, priority, detail, source, secondary = '') => ({
  'Nombre completo': name, 'Cargo actual': role, 'Empresa u organización': org, Grupo: group, 'Subcategoría': sub, Ciudad: city,
  LinkedIn: linkedin, Instagram: '', 'Sitio web': '', 'Correo profesional público': '', 'Canal recomendado de contacto': 'LinkedIn',
  'Eventos o proyectos relacionados': event, 'Evidencia de actividad reciente': activity, 'Razón por la que es relevante': relevance,
  'Potencial para aportar al estudio, del 1 al 5': contribution, 'Capacidad de abrir otras puertas, del 1 al 5': doors,
  'Facilidad estimada de contacto, del 1 al 5': ease, 'Prioridad total': priority, 'Detalle concreto para personalizar el mensaje': detail,
  'Clasificación de priorización': priority >= 12 && ease >= 4 ? 'Contactar primero' : doors >= 5 ? 'Conectores' : priority < 10 ? 'Investigar más' : 'Buscar una presentación',
  'Copy personalizado': `Hola, ${name.split(' ')[0]}, ¿cómo estás?\n\nSoy Alejandro. Durante los últimos años me he dedicado a diseñar tecnología que ayuda a las empresas a simplificar procesos y mejorar sus operaciones.\n\nActualmente estoy desarrollando un estudio independiente para entender cómo operan realmente las productoras y organizadores de eventos en Perú.\n\n${detail} y creo que sería muy valioso incluir también tu perspectiva.\n\n¿Crees que podamos conversar unos 20 minutos esta o la próxima semana?`,
  'Fuente principal': source, 'Fuentes secundarias': secondary, 'Fecha de verificación': checked, 'Nivel de confianza: alto, medio o bajo': 'alto',
  'Estado de verificación al 18-07-2026': 'Pendiente de contraste adicional',
  'Decisión de investigación': 'Mantener en investigación'
});

const rows = [
  base('Mariana Benavente','Co-founder y CEO','MBE Luxury & Events','Fundadores','Productora / experiencias','Lima','', 'MarianaBé / MBE; European Brunch y Masquerade Brunch','Web oficial describe 22 eventos desde 2023 y próximos eventos.','Fundó el proyecto y dirige una productora activa de experiencias. ',5,4,4,13,'Vi que fundaste MarianaBé y que MBE reporta 22 experiencias desde 2023, incluyendo brunches temáticos en Lima.','https://www.mbeproductions.com/'),
  base('Milagros Benavente','Co-founder y CFO','MBE Luxury & Events','Fundadores','Productora / experiencias','Lima','', 'MBE Luxury & Events','Web oficial la identifica como cofundadora y parte del equipo núcleo.','Cofundadora de una marca de eventos activa en Lima.',4,4,4,12,'Vi que eres parte del equipo fundador de MBE y que el proyecto viene consolidando experiencias temáticas en Lima.','https://www.mbeproductions.com/'),
  base('Milagros Flores','Co-founder y COO','MBE Luxury & Events','Operaciones','Operaciones de productora','Lima','', 'MBE Luxury & Events','Web oficial identifica su rol COO y foco en coordinación de eventos.','Perfil operativo de una productora activa, con visión de coordinación y detalle.',5,4,4,13,'Vi que como COO de MBE coordinas la organización de experiencias con foco en ejecución y detalle.','https://www.mbeproductions.com/'),
  base('Samantha Llaque Ulloa','Gerente de producción','Eventrade Productora de Eventos','Operaciones','Producción de eventos','Lima / Surco','https://pe.linkedin.com/in/sllaqueulloa','Eventrade','Perfil actual de LinkedIn indica el cargo Gerente de producción en Eventrade.','Experiencia directa y actividad pública reciente sobre la operación de eventos.',5,3,4,12,'Vi tu trabajo como gerente de producción en Eventrade y tus reflexiones recientes sobre la realidad operativa del event planning.','https://pe.linkedin.com/in/sllaqueulloa'),
  base('Víctor Fabian Brittos Rivera','Productor de eventos','Local Crew Perú / VB Technical Events','Operaciones','Producción técnica','Lima','https://pe.linkedin.com/in/v%C3%ADctor-fabian-brittos-rivera-b029b352','Mon Laferte Lima; London Symphony Orchestra para TQ Producciones','Perfil registra producción de conciertos y proyectos en Lima.','Aporta la perspectiva técnica y de producción de conciertos.',5,4,3,12,'Vi que has participado en la producción de conciertos en Lima, incluyendo Mon Laferte y la London Symphony Orchestra para TQ Producciones.','https://pe.linkedin.com/in/v%C3%ADctor-fabian-brittos-rivera-b029b352'),
  base('Jessica Sherrit Mago','Líder de ejecución de Experiencias BTL','Grupo Kandavu','Operaciones','Experiencias BTL','Lima','https://pe.linkedin.com/in/jessica-sherrit-mago-7605b767','Festival de rock de Kandavu','Publicación de hace 6 meses señala que Kandavu le propuso liderar ejecución BTL.','Rol reciente de ejecución en una productora relevante.',5,4,3,12,'Vi que Kandavu te convocó para liderar la ejecución de experiencias BTL en un festival de rock.','https://pe.linkedin.com/in/jessica-sherrit-mago-7605b767'),
  base('Sophia Ugarte León','Profesional de eventos corporativos','Grupo Kandavu','Operaciones','Eventos / BTL','Lima','https://pe.linkedin.com/in/sophia-ugarte-le%C3%B3n-11b9b8aa','Digitruck; eventos corporativos Kandavu','Perfil público vincula a Grupo Kandavu y describe ejecución integral; fuente indexada hace 4 días.','Está vinculada públicamente a una productora multiservicio y comparte un canal profesional.',4,4,5,13,'Vi tu trabajo en Grupo Kandavu y la propuesta de ejecutar experiencias corporativas desde la idea hasta la implementación.','https://pe.linkedin.com/in/sophia-ugarte-le%C3%B3n-11b9b8aa'),
  base('Iliana Gil Rojas','Coordinadora de Producción','Tupaq Producciones','Operaciones','Producción BTL','Miraflores','', 'Tupaq: eventos y activaciones BTL','Publicación de empleo de hace 7 meses la identifica como coordinadora de producción.','Coordinación operativa en productora BTL con proyectos para marcas.',5,3,4,12,'Vi que coordinas producción en Tupaq, una productora que ejecuta eventos y activaciones BTL para distintas marcas.','https://pe.linkedin.com/jobs/view/director-de-producci%C3%B3n-at-tupaq-producciones-4035377101'),
  base('Zoila Espinoza Guerrero','Productora freelance / Coordinadora de producción y logística','Independiente','Organizadores independientes','Producción, protocolo y logística','Lima','https://pe.linkedin.com/in/zoilaespinoza','EXCON, PERUMIN, ASBANC TECH, Wine Fest','Perfil documenta cartera de proyectos 2023–2024 y tareas de coordinación.','Experiencia transversal en producción, sala, protocolo y logística.',5,4,4,13,'Vi que has coordinado producción y logística en eventos como EXCON, PERUMIN, ASBANC TECH y Wine Fest.','https://pe.linkedin.com/in/zoilaespinoza'),
  base('Jagoda Vasquez','Organizadora y gestora cultural','Festival Despertar','Organizadores independientes','Festival cultural / bienestar','Lima','https://pe.linkedin.com/in/jagoda-vasquez','Festival Despertar; Ciclos Fest','Perfil documenta gestión y ejecución del Festival Despertar y apoyo en Ciclos Fest en 2025.','Organiza y opera un festival con artistas, proveedores y logística.',5,3,4,12,'Vi que como gestora del Festival Despertar coordinaste programación, artistas, proveedores y logística del evento.','https://pe.linkedin.com/in/jagoda-vasquez'),
  base('Jharlen Osnar Ormeño Solano','Productor de eventos y arte-educador','Productora Creativa Huellas de Arena','Organizadores independientes','Producción cultural','Lima','https://pe.linkedin.com/in/jharlen-osnar-orme%C3%B1o-solano-100514170','Huellas de Arena','Perfil se identifica como productor de eventos en Lima y muestra actividad reciente.','Perfil independiente de producción cultural activo públicamente.',4,3,4,11,'Vi tu trabajo como productor de eventos y arte-educador en Productora Creativa Huellas de Arena.','https://pe.linkedin.com/in/jharlen-osnar-orme%C3%B1o-solano-100514170'),
  base('Carlos Tenicela','Director y Fundador','Instituto de Protocolo y Eventos S.A.C.','Fundadores','Protocolo y gestión de eventos','Lima','https://pe.linkedin.com/in/carlostenicela','Masterclass de organización de eventos; operación LCC/Westin','Perfil señala fundador desde 2016 y actividad de formación reciente; referencias describen experiencia operativa.','Conecta formación, protocolo y ejecución institucional/corporativa.',5,5,4,14,'Vi que fundaste el Instituto de Protocolo y Eventos y que recientemente compartiste una masterclass sobre organización eficiente de eventos.','https://pe.linkedin.com/in/carlostenicela'),
  base('Víctor Muñoz Lecaros','Co-Founder','Maga Eventos','Fundadores','Agencia de eventos corporativos','Miraflores','', 'Maga Eventos','Oferta publicada hace 5 meses lo identifica como cofundador y presenta la agencia como eventos exclusivos.','Cofundador de agencia con contratación reciente de producción presencial.',5,4,4,13,'Vi que eres cofundador de Maga Eventos y que el equipo ha estado buscando producción para eventos corporativos presenciales.','https://pe.linkedin.com/jobs/view/productor-de-eventos-at-maga-eventos-y-btl-4357860140'),
  base('Diego Huamán Hernández','Director y socio fundador','Oranch','Fundadores','Representación de artistas / espectáculos','Lima','', 'Oranch; Los Productores; La Plaza; Sala de Parto','Lima Pro lo identifica como director y socio fundador de una productora-promotora de espectáculos en vivo desde 2017.','Conecta representación de artistas y producción/promoción de espectáculos.',5,5,3,13,'Vi que desde Oranch trabajas en representación de artistas y producción-promoción de espectáculos en vivo.','https://limapro.pe/'),
  base('Christian Ricardo','Fundador y Gerente General','La Marka Agencia','Fundadores','Entretenimiento / eventos de freestyle','Lima','', 'Eventos de freestyle en Lima, provincias e internacional','Lima Pro lo identifica como fundador y gerente; describe producción de eventos en Lima y más de diez provincias.','Opera eventos y tiene red territorial en entretenimiento.',5,5,3,13,'Vi que fundaste La Marka Agencia y que vienes produciendo eventos de freestyle en Lima y en distintas provincias.','https://limapro.pe/'),
  base('Danneth Valeriano','CEO y Fundadora; Press Manager','Biscuitbatik / CABS Management','Conectores','Management y PR musical','Lima','', 'Indie.gestión; CABS Management','Lima Pro la presenta como CEO/fundadora, press manager y parte de management.','Conectora entre artistas, management y producción independiente.',4,5,3,12,'Vi tu rol como CEO y fundadora de Biscuitbatik y tu trabajo de press management y gestión en la escena independiente.','https://limapro.pe/'),
  base('Alejandro Noriega','Productor Ejecutivo y Fundador','Rebeca','Fundadores','Producción ejecutiva','Lima','', 'Rebeca','Programa de El Ojo de Iberoamérica identifica explícitamente el cargo y empresa.','Fundador con responsabilidad ejecutiva de producción.',4,4,2,10,'Vi que eres productor ejecutivo y fundador de Rebeca, con experiencia reconocida en la industria de producción.','https://www.elojodeiberoamerica.com/files/pdf/es/Programa-ElOjo2018.pdf'),
  base('Paola Pastrana','Productora Ejecutiva','Cine 70 Films','Fundadores','Producción ejecutiva','Lima','', 'Cine 70 Films','Programa de El Ojo de Iberoamérica la identifica como productora ejecutiva de Cine 70 Films.','Aporta experiencia ejecutiva de producción y red audiovisual vinculada a eventos.',4,4,2,10,'Vi tu trabajo como productora ejecutiva de Cine 70 Films y me interesaría incorporar tu perspectiva de producción.','https://www.elojodeiberoamerica.com/files/pdf/es/Programa-ElOjo2018.pdf'),
  base('Jhivan Centeno','Cofundador','BENNU Productora de Eventos','Fundadores','Productora de eventos','Huancayo / expansión a Lima','', 'BENNU','Programa de Perú Bodas y Eventos identifica a Jhivan y Roberto como fundadores en 2023 y anuncia expansión a Lima en 2026.','Fundador de productora que se expande a Lima; buena perspectiva de crecimiento.',4,4,3,11,'Vi que cofundaste BENNU y que la productora está preparando su expansión a Lima.','https://perubodasyeventos.com/programa/'),
  base('Roberto Pino','Cofundador','BENNU Productora de Eventos','Fundadores','Productora de eventos','Huancayo / expansión a Lima','', 'BENNU','Programa de Perú Bodas y Eventos identifica a Jhivan y Roberto como fundadores en 2023 y anuncia expansión a Lima en 2026.','Fundador de productora en crecimiento con futura presencia limeña.',4,4,3,11,'Vi que cofundaste BENNU y que el equipo está proyectando llevar su propuesta de eventos a Lima.','https://perubodasyeventos.com/programa/'),
  base('Yunko','Fundador','Llegó la hora de volar','Fundadores','Event planning / diseño y producción','Lima','', 'Llegó la hora de volar','Programa lo describe como event planner peruano con más de 25 años y fundador de su marca.','Veterano del sector; alta capacidad de conectar con otros proveedores.',5,5,2,12,'Vi que fundaste Llegó la hora de volar y llevas más de 25 años combinando diseño y producción de experiencias.','https://perubodasyeventos.com/programa/'),
  base('Sergio Roncal Ugaz','Profesional vinculado a Bizarro Live Entertainment','Bizarro Live Entertainment','Operaciones','Entretenimiento en vivo','Lima / San Luis','https://pe.linkedin.com/in/sergioroncalugaz','Bizarro Live Entertainment','Perfil actualizado hace 3 semanas muestra relación con Bizarro y actividad pública.','Acceso potencial a un gran operador de entretenimiento; cargo exacto no visible en la fuente indexada.',3,4,3,10,'Vi tu vínculo actual con Bizarro Live Entertainment en Lima; me gustaría conocer tu mirada sobre la operación de entretenimiento en vivo.','https://pe.linkedin.com/in/sergioroncalugaz'),
  base('Kimberly Mas Risso','Profesional de industria musical y eventos en vivo','Bizarro Live Entertainment','Operaciones','Venue management / producción','Lima','https://pe.linkedin.com/in/kimmorer','HA*ASH, Gloria Trevi y Airbag; evento deportivo en Asia','Perfil describe 10 años en música/eventos en vivo y actividad sobre venue manager/producer; referencia a sold-outs.','Experiencia reciente en producción y operación de eventos en vivo.',5,4,3,12,'Vi tu experiencia en la industria musical y de eventos en vivo, y tu participación reciente en producción y venue management.','https://pe.linkedin.com/in/kimmorer'),
  base('Daniela Tacza','Profesional vinculada a Kandavu Producciones','Kandavu Producciones','Operaciones','Producción de eventos','Lima','https://pe.linkedin.com/in/daniela-tacza-72902b37a','Kandavu Producciones','Perfil indexado hace 4 días indica Lima y Kandavu; cargo no visible.','Vínculo actual muy reciente con productora relevante; requiere confirmar el cargo antes de escribir.',3,3,3,9,'Vi tu vínculo actual con Kandavu Producciones en Lima y me gustaría conocer tu perspectiva sobre la operación del sector.','https://pe.linkedin.com/in/daniela-tacza-72902b37a'),
  base('José Luis Capdevila Alva','Director Creativo','Grupo Kandavu','Operaciones','Diseño / experiencias BTL','Lima','https://pe.linkedin.com/in/josecapdevila','Grupo Kandavu; Klikealo','Directorio de personal de Grupo Kandavu lo identifica como Director Creativo; LinkedIn confirma vínculo actual.','Aporta la intersección entre diseño creativo y ejecución de experiencias; vínculo actual confirmado.',4,4,3,11,'Vi tu trabajo como Director Creativo en Grupo Kandavu y me interesaría conocer cómo se conecta el diseño de experiencias con la ejecución operativa.','https://contactout.com/company/Grupo-Kandavu-90511','https://pe.linkedin.com/in/josecapdevila'),
  base('Carlos Mendoza','Gerente de Desarrollo Económico','Miura Stage','Conectores','Escenarios, sonido e iluminación','Huancayo / cobertura Lima','', 'Miura Stage','Web vigente identifica cargo y prestación de escenarios, sonido e iluminación para eventos en Perú, incluido Lima.','Proveedor técnico que trabaja con diversos organizadores; conector útil aunque no opera desde Lima.',4,4,3,11,'Vi que desde Miura Stage trabajan escenarios, sonido e iluminación para conciertos y eventos en distintas ciudades, incluido Lima.','https://miurastage.com/'),
];

const headers = Object.keys(rows[0]);
rows.find((row) => row['Nombre completo'] === 'Sophia Ugarte León')['Correo profesional público'] = 's.ugarte@kandavubtl.com';
const revise = (name, changes) => Object.assign(rows.find((row) => row['Nombre completo'] === name), changes);

revise('Mariana Benavente', { 'Cargo actual': 'Cofounder y Executive Director (MBE)', Ciudad: 'Zúrich / proyectos en Sudamérica', Instagram: 'https://www.instagram.com/marianabenavente/', 'Sitio web': 'https://mbeluxuryevents.com/', 'Evidencia de actividad reciente': 'LinkedIn la muestra como Cofounder and Executive Director de MBE en Zúrich y Sudamérica. La web MBE 2026 anuncia Wedding Weekend 2026 en Lima; no prueba que Mariana opere localmente en Lima hoy.', 'Estado de verificación al 18-07-2026': 'Rol y empresa actuales confirmados; presencia personal en Lima no confirmada.', 'Decisión de investigación': 'Mantener como contacto internacional; no asumir operación local.', 'Fuentes secundarias': 'https://ch.linkedin.com/in/mariana-benavente-18408a295 | https://mbeluxuryevents.com/', 'Nivel de confianza: alto, medio o bajo': 'alto' });
revise('Milagros Benavente', { 'Cargo actual': 'Insight & Marketing Consultant (perfil público)', Ciudad: 'No verificada para operación de eventos en Lima', LinkedIn: 'https://de.linkedin.com/in/milagros-benavente', 'Evidencia de actividad reciente': 'El perfil público indexado la presenta como Insight & Marketing Consultant. No se corroboró una vinculación individual actual con MBE ni un rol operativo en eventos.', 'Estado de verificación al 18-07-2026': 'No cumple la verificación mínima como perfil operativo/de decisor de eventos.', 'Decisión de investigación': 'Excluir de la lista activa; conservar en auditoría.', 'Nivel de confianza: alto, medio o bajo': 'medio' });
revise('Milagros Flores', { 'Cargo actual': 'No verificado', 'Empresa u organización': 'No verificada', 'Evidencia de actividad reciente': 'MBE sigue activa y anuncia Wedding Weekend 2026 en Lima, pero ni la web actual ni una búsqueda pública del perfil individual permiten confirmar que Milagros Flores continúe como COO. Los resultados de LinkedIn para ese nombre corresponden a otras personas.', 'Estado de verificación al 18-07-2026': 'No se pudo desambiguar ni confirmar identidad, cargo o vínculo vigente.', 'Decisión de investigación': 'Excluir de la lista activa; conservar en auditoría.', 'Nivel de confianza: alto, medio o bajo': 'bajo' });
revise('Samantha Llaque Ulloa', { 'Estado de verificación al 18-07-2026': 'LinkedIn confirma: Gerente de producción en Eventrade.', 'Decisión de investigación': 'Contacto prioritario.' });
revise('Víctor Fabian Brittos Rivera', { 'Cargo actual': 'Propietario y productor', 'Empresa u organización': 'Local Crew Perú', 'Evidencia de actividad reciente': 'LinkedIn confirma el titular “Propietario y Productor Local Crew Perú”.', 'Estado de verificación al 18-07-2026': 'Cargo y empresa actuales confirmados.', 'Decisión de investigación': 'Contacto prioritario.' });
revise('Jessica Sherrit Mago', { 'Evidencia de actividad reciente': 'La evidencia anterior identifica trabajo de ejecución BTL en Kandavu, pero el perfil no expuso cargo actual durante la revisión.', 'Estado de verificación al 18-07-2026': 'Vínculo y evidencia reciente de ejecución, cargo actual pendiente.', 'Decisión de investigación': 'Investigar más antes de usar cargo en el mensaje.', 'Nivel de confianza: alto, medio o bajo': 'medio' });
revise('Sophia Ugarte León', { 'Cargo actual': 'Account Executive', 'Empresa u organización': 'Grupo Kandavu Brand Service', 'Evidencia de actividad reciente': 'LinkedIn la identifica como ejecutiva de Grupo Kandavu y la página de Kandavu Brand Service la lista como Account Executive. Su perfil ofrece ejecutar eventos corporativos desde la idea hasta la implementación; la actividad visible es histórica.', 'Estado de verificación al 18-07-2026': 'Empresa y cargo actuales confirmados; responsabilidad operativa directa no totalmente expuesta.', 'Decisión de investigación': 'Mantener como contacto BTL secundario; no presentarla como responsable de operaciones.', 'Fuente principal': 'https://pe.linkedin.com/in/sophia-ugarte-le%C3%B3n-11b9b8aa', 'Fuentes secundarias': 'https://pe.linkedin.com/company/kandavu-brandservice', 'Nivel de confianza: alto, medio o bajo': 'alto' });
revise('Iliana Gil Rojas', { LinkedIn: 'https://pe.linkedin.com/in/iliana-lizet-bach-agronomia', 'Evidencia de actividad reciente': 'Perfil público de LinkedIn confirma: Coordinadora de Producción en Tupaq Producciones.', 'Estado de verificación al 18-07-2026': 'Cargo y empresa actuales confirmados.', 'Decisión de investigación': 'Contacto prioritario.' });
revise('Zoila Espinoza Guerrero', { 'Evidencia de actividad reciente': 'El perfil documenta 19 eventos como productora freelance durante 2023–2024. Hay reacciones públicas en 2026, pero no evidencia de una nueva producción o encargo operativo desde enero de 2025.', 'Estado de verificación al 18-07-2026': 'Experiencia comprobada; vigencia operativa 2025–2026 no confirmada.', 'Decisión de investigación': 'Investigar más; no priorizar contacto en frío.', 'Nivel de confianza: alto, medio o bajo': 'medio' });
revise('Jagoda Vasquez', { 'Cargo actual': 'Profesional independiente / gestora cultural', 'Empresa u organización': 'Independiente', 'Evidencia de actividad reciente': 'LinkedIn confirma que organizó y gestionó Festival Despertar (jun–sep 2024), apoyó producción y coordinación operativa de Ciclos Fest en Lima (feb 2025), y participó en coordinación de residencia cultural en Perú (ago–oct 2025).', 'Estado de verificación al 18-07-2026': 'Especialidad, rol de organización y actividad operativa reciente confirmados.', 'Decisión de investigación': 'Contacto prioritario para el segmento cultural/independiente.', 'Fuente principal': 'https://pe.linkedin.com/in/jagoda-vasquez', 'Nivel de confianza: alto, medio o bajo': 'alto' });
revise('Jharlen Osnar Ormeño Solano', { 'Cargo actual': 'CEO', 'Empresa u organización': 'Productora Creativa Huellas de Arena', 'Evidencia de actividad reciente': 'LinkedIn confirma el titular CEO de Productora Creativa Huellas de Arena.', 'Estado de verificación al 18-07-2026': 'Cargo y empresa actuales confirmados.', 'Decisión de investigación': 'Contacto prioritario.' });
revise('Carlos Tenicela', { 'Cargo actual': 'Experto en protocolo de Estado e identidad nacional', 'Empresa u organización': 'Fundación por el Perú', 'Evidencia de actividad reciente': 'LinkedIn se presenta como Experto en protocolo de Estado e identidad nacional y muestra Fundación por el Perú; no confirmó durante la revisión su cargo actual como director del Instituto de Protocolo y Eventos.', 'Estado de verificación al 18-07-2026': 'Especialidad y organización actuales visibles; rol de fundador del instituto pendiente.', 'Decisión de investigación': 'Conector útil, pero escribir desde protocolo y no atribuir cargo no confirmado.', 'Nivel de confianza: alto, medio o bajo': 'medio' });
revise('Víctor Muñoz Lecaros', { LinkedIn: 'https://pe.linkedin.com/in/v%C3%ADctor-mu%C3%B1oz-lecaros-524164117', 'Sitio web': 'https://magaeventos.com/', 'Cargo actual': 'Co-Founder', 'Evidencia de actividad reciente': 'LinkedIn lo presenta como Co-Founder de Maga Eventos. Publicaciones y vacantes de Maga de los últimos días/semanas muestran producción de eventos corporativos y BTL; su perfil cita proyectos de implementación como Nike “Toma El Juego” y Comfortia.', 'Estado de verificación al 18-07-2026': 'Cargo, empresa y actividad de la agencia confirmados.', 'Decisión de investigación': 'Contacto prioritario.', 'Fuente principal': 'https://pe.linkedin.com/in/v%C3%ADctor-mu%C3%B1oz-lecaros-524164117', 'Fuentes secundarias': 'https://www.linkedin.com/company/magaeventos-peru | https://pe.linkedin.com/jobs/view/asistente-de-cuentas-at-maga-eventos-4371092013', 'Nivel de confianza: alto, medio o bajo': 'alto' });
revise('Diego Huamán Hernández', { LinkedIn: 'https://pe.linkedin.com/in/diegohuamanh', Instagram: 'https://www.instagram.com/diegohuamanh/', 'Cargo actual': 'Director General (perfil público)', 'Evidencia de actividad reciente': 'LinkedIn público lo identifica como Director General; Oranch mantiene página corporativa activa. “Socio fundador” y proyectos específicos requieren confirmación.', 'Estado de verificación al 18-07-2026': 'Identidad, rol directivo y vínculo con Oranch corroborados.', 'Decisión de investigación': 'Contacto prioritario; personalizar sólo con Oranch y espectáculos en vivo.' });
revise('Christian Ricardo', { 'Nombre completo': 'Christian Colán', 'Cargo actual': 'CEO y titular-gerente', 'Empresa u organización': 'La Marka Agencia / La Marka Entretenimiento E.I.R.L.', Instagram: 'https://www.instagram.com/lamarka.agencia/', 'Evidencia de actividad reciente': 'Gestión (mayo 2025) identifica a Christian Colán como fundador y CEO. El directorio corporativo lo lista como titular-gerente desde 2021 y la página de La Marka publicó hace cuatro semanas la producción integral de ROK TECH PE 2026; la empresa también comunica producción de FMS Perú.', 'Estado de verificación al 18-07-2026': 'Identidad, posición de decisión y actividad reciente de la empresa confirmadas.', 'Decisión de investigación': 'Contacto prioritario.', 'Fuente principal': 'https://gestion.pe/empresasg/la-marka-caso-de-exito-de-una-agencia-creativa-y-joven-que-revoluciona-el-marketing-en-peru-noticia/', 'Fuentes secundarias': 'https://pe.linkedin.com/company/la-marka-agencia | https://www.datosperu.org/empresa-la-marka-entretenimiento-eirl-20607786730.php', 'Nivel de confianza: alto, medio o bajo': 'alto' });
revise('Danneth Valeriano', { LinkedIn: 'https://pe.linkedin.com/in/dannethvalerianolopez', 'Cargo actual': 'Periodista musical / Agencia Indie.gestión', 'Empresa u organización': 'Agencia Indie.gestión / Biscuitbatik', 'Evidencia de actividad reciente': 'LinkedIn la vincula actualmente a Agencia Indie.gestión y describe a Biscuitbatik como un medio independiente de música, noticias y conciertos. La actividad pública visible más reciente es de hace 12 meses.', 'Estado de verificación al 18-07-2026': 'Vínculo actual con la escena musical confirmado; no se confirmó que dirija CABS Management ni una responsabilidad de operación de eventos.', 'Decisión de investigación': 'Conector secundario; no presentarla como CEO ni productora.', 'Fuente principal': 'https://pe.linkedin.com/in/dannethvalerianolopez', 'Fuentes secundarias': 'https://limapro.pe/', 'Nivel de confianza: alto, medio o bajo': 'alto' });
revise('Alejandro Noriega', { LinkedIn: 'https://pe.linkedin.com/in/alejandro-noriega-maldonado', 'Cargo actual': 'Productor ejecutivo y fundador', 'Empresa u organización': 'Rebeca Producciones', 'Evidencia de actividad reciente': 'LinkedIn lo ubica en Rebeca Producciones. Una publicación de hace cinco días lo identifica como productor ejecutivo y fundador; su actividad reciente se concentra en producción audiovisual publicitaria.', 'Estado de verificación al 18-07-2026': 'Cargo y empresa corroborados, pero su operación es audiovisual y no de eventos.', 'Decisión de investigación': 'Excluir de la lista activa; conservar como contacto adyacente.', 'Fuente principal': 'https://pe.linkedin.com/in/alejandro-noriega-maldonado', 'Fuentes secundarias': 'https://es.linkedin.com/posts/adrianalbujar_debrief-activity-7449263211346214912', 'Nivel de confianza: alto, medio o bajo': 'alto' });
revise('Paola Pastrana', { LinkedIn: 'https://pe.linkedin.com/in/paola-pastrana-1989b185', 'Cargo actual': 'Directora de Producción', 'Empresa u organización': 'Studio V', 'Evidencia de actividad reciente': 'LinkedIn la identifica como Directora de Producción de Studio V. Cine70 es relación histórica, no empleo actual comprobado.', 'Estado de verificación al 18-07-2026': 'Cargo actual corroborado, pero es producción audiovisual y no operación de eventos.', 'Decisión de investigación': 'Excluir de la lista activa; conservar en auditoría.' });
revise('Jhivan Centeno', { Instagram: 'https://www.instagram.com/bennu_productora/', 'Evidencia de actividad reciente': 'El programa vigente de Perú Bodas y Eventos identifica a Jhivan Centeno y Roberto Pino como fundadores de BENNU en 2023 y anuncia expansión de la productora a Lima en 2026.', 'Estado de verificación al 18-07-2026': 'Rol de fundador y expansión 2026 confirmados por fuente sectorial; perfil individual público no localizado.', 'Decisión de investigación': 'Mantener; buscar presentación o contacto por la marca.', 'Nivel de confianza: alto, medio o bajo': 'medio' });
revise('Roberto Pino', { Instagram: 'https://www.instagram.com/bennu_productora/', 'Evidencia de actividad reciente': 'El programa vigente de Perú Bodas y Eventos identifica a Jhivan Centeno y Roberto Pino como fundadores de BENNU en 2023 y anuncia expansión de la productora a Lima en 2026.', 'Estado de verificación al 18-07-2026': 'Rol de fundador y expansión 2026 confirmados por fuente sectorial; perfil individual público no localizado.', 'Decisión de investigación': 'Mantener; buscar presentación o contacto por la marca.', 'Nivel de confianza: alto, medio o bajo': 'medio' });
revise('Yunko', { Instagram: 'https://www.instagram.com/yunko_llegolahoradevolarperu/', 'Evidencia de actividad reciente': 'La cuenta oficial anuncia Llegó la hora de volar Perú 2026 y una publicación de noviembre de 2025 confirmó una fecha en Lima.', 'Estado de verificación al 18-07-2026': 'Marca, actividad 2025–2026 y conexión con Lima corroboradas.', 'Decisión de investigación': 'Conector prioritario; buscar persona de contacto directa desde la cuenta oficial.' });
revise('Sergio Roncal Ugaz', { 'Cargo actual': 'Gerente General', 'Empresa u organización': 'Media Pro Producción y Eventos', 'Evidencia de actividad reciente': 'LinkedIn se presenta como “Gerente General - Media Pro Producción y Eventos”; Bizarro aparece en trayectoria, sin probar que sea empleo actual.', 'Estado de verificación al 18-07-2026': 'Cargo actual en Media Pro confirmado; no atribuir cargo actual en Bizarro.', 'Decisión de investigación': 'Contacto prioritario.' });
revise('Kimberly Mas Risso', { 'Cargo actual': 'Marketing | Entertainment Industry | Concerts', 'Empresa u organización': 'Live Nation Entertainment', 'Evidencia de actividad reciente': 'LinkedIn muestra el titular Marketing | Entertainment Industry | Concerts y Live Nation Entertainment. No se corroboró empleo actual en Bizarro ni rol operativo.', 'Estado de verificación al 18-07-2026': 'Perfil actual confirmado, pero no corresponde al grupo de operaciones requerido.', 'Decisión de investigación': 'Excluir de la lista activa; conservar en auditoría.' });
revise('Daniela Tacza', { 'Cargo actual': 'Community Manager', 'Evidencia de actividad reciente': 'LinkedIn confirma: Community Manager en Kandavu Producciones.', 'Estado de verificación al 18-07-2026': 'Perfil actual confirmado, pero excluido por no tener responsabilidad operativa.', 'Decisión de investigación': 'Excluir de la lista activa; conservar en auditoría.' });
revise('José Luis Capdevila Alva', { 'Cargo actual': 'Director Creativo', 'Empresa u organización': 'Klikealo LATAM - Grupo Kandavu', 'Evidencia de actividad reciente': 'LinkedIn confirma el titular “Director Creativo en Klikealo LATAM - Grupo KANDAVU”.', 'Estado de verificación al 18-07-2026': 'Cargo y vínculo actual confirmados.', 'Decisión de investigación': 'Conector relevante entre creatividad y ejecución.' });
revise('Carlos Mendoza', { 'Evidencia de actividad reciente': 'La web oficial de Miura Stage 2026 identifica a Carlos Mendoza como Gerente de Desarrollo Económico y ofrece escenarios, sonido e iluminación para Perú, incluido Lima y Huancayo.', 'Estado de verificación al 18-07-2026': 'Cargo, empresa y servicios confirmados en web oficial.', 'Decisión de investigación': 'Conector técnico prioritario.' });
const quote = (v) => `"${String(v ?? '').replaceAll('"','""')}"`;
const activeRows = rows.filter((row) => !['Milagros Benavente', 'Milagros Flores', 'Paola Pastrana', 'Kimberly Mas Risso', 'Daniela Tacza', 'Alejandro Noriega'].includes(row['Nombre completo']));
await fs.mkdir('research/outputs', { recursive: true });
await fs.writeFile('research/outputs/contactos_eventos_peru_verificados.csv', [headers.map(quote).join(','), ...rows.map(r => headers.map(h => quote(r[h])).join(','))].join('\n'), 'utf8');
await fs.writeFile('research/outputs/contactos_eventos_peru_activos.csv', [headers.map(quote).join(','), ...activeRows.map(r => headers.map(h => quote(r[h])).join(','))].join('\n'), 'utf8');
await fs.writeFile('research/outputs/resumen_research.json', JSON.stringify(rows, null, 2), 'utf8');
console.log(`Auditados ${rows.length}; activos ${activeRows.length}`);
