// AUTOGENERADO por scratchpad/gen-countries.mjs — no editar a mano.
// Fuente única de países para el selector de teléfono y el reporte. Refleja la
// tabla `country` de la DB (mismo code/dial/label).
export type Country = { code: string; dial: string; label: string; flag: string };

export const COUNTRIES: Country[] = [
  { code: "AF", dial: "93", label: "Afganistán", flag: "🇦🇫" },
  { code: "AL", dial: "355", label: "Albania", flag: "🇦🇱" },
  { code: "DE", dial: "49", label: "Alemania", flag: "🇩🇪" },
  { code: "AD", dial: "376", label: "Andorra", flag: "🇦🇩" },
  { code: "AO", dial: "244", label: "Angola", flag: "🇦🇴" },
  { code: "AG", dial: "1", label: "Antigua y Barbuda", flag: "🇦🇬" },
  { code: "SA", dial: "966", label: "Arabia Saudí", flag: "🇸🇦" },
  { code: "DZ", dial: "213", label: "Argelia", flag: "🇩🇿" },
  { code: "AR", dial: "54", label: "Argentina", flag: "🇦🇷" },
  { code: "AM", dial: "374", label: "Armenia", flag: "🇦🇲" },
  { code: "AW", dial: "297", label: "Aruba", flag: "🇦🇼" },
  { code: "AU", dial: "61", label: "Australia", flag: "🇦🇺" },
  { code: "AT", dial: "43", label: "Austria", flag: "🇦🇹" },
  { code: "AZ", dial: "994", label: "Azerbaiyán", flag: "🇦🇿" },
  { code: "BS", dial: "1", label: "Bahamas", flag: "🇧🇸" },
  { code: "BD", dial: "880", label: "Bangladés", flag: "🇧🇩" },
  { code: "BB", dial: "1", label: "Barbados", flag: "🇧🇧" },
  { code: "BH", dial: "973", label: "Baréin", flag: "🇧🇭" },
  { code: "BE", dial: "32", label: "Bélgica", flag: "🇧🇪" },
  { code: "BZ", dial: "501", label: "Belice", flag: "🇧🇿" },
  { code: "BJ", dial: "229", label: "Benín", flag: "🇧🇯" },
  { code: "BY", dial: "375", label: "Bielorrusia", flag: "🇧🇾" },
  { code: "BO", dial: "591", label: "Bolivia", flag: "🇧🇴" },
  { code: "BA", dial: "387", label: "Bosnia y Herzegovina", flag: "🇧🇦" },
  { code: "BW", dial: "267", label: "Botsuana", flag: "🇧🇼" },
  { code: "BR", dial: "55", label: "Brasil", flag: "🇧🇷" },
  { code: "BN", dial: "673", label: "Brunéi", flag: "🇧🇳" },
  { code: "BG", dial: "359", label: "Bulgaria", flag: "🇧🇬" },
  { code: "BF", dial: "226", label: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", dial: "257", label: "Burundi", flag: "🇧🇮" },
  { code: "BT", dial: "975", label: "Bután", flag: "🇧🇹" },
  { code: "CV", dial: "238", label: "Cabo Verde", flag: "🇨🇻" },
  { code: "KH", dial: "855", label: "Camboya", flag: "🇰🇭" },
  { code: "CM", dial: "237", label: "Camerún", flag: "🇨🇲" },
  { code: "CA", dial: "1", label: "Canadá", flag: "🇨🇦" },
  { code: "QA", dial: "974", label: "Catar", flag: "🇶🇦" },
  { code: "TD", dial: "235", label: "Chad", flag: "🇹🇩" },
  { code: "CZ", dial: "420", label: "Chequia", flag: "🇨🇿" },
  { code: "CL", dial: "56", label: "Chile", flag: "🇨🇱" },
  { code: "CN", dial: "86", label: "China", flag: "🇨🇳" },
  { code: "CY", dial: "357", label: "Chipre", flag: "🇨🇾" },
  { code: "VA", dial: "379", label: "Ciudad del Vaticano", flag: "🇻🇦" },
  { code: "CO", dial: "57", label: "Colombia", flag: "🇨🇴" },
  { code: "KM", dial: "269", label: "Comoras", flag: "🇰🇲" },
  { code: "CG", dial: "242", label: "Congo", flag: "🇨🇬" },
  { code: "KP", dial: "850", label: "Corea del Norte", flag: "🇰🇵" },
  { code: "KR", dial: "82", label: "Corea del Sur", flag: "🇰🇷" },
  { code: "CR", dial: "506", label: "Costa Rica", flag: "🇨🇷" },
  { code: "CI", dial: "225", label: "Côte d’Ivoire", flag: "🇨🇮" },
  { code: "HR", dial: "385", label: "Croacia", flag: "🇭🇷" },
  { code: "CU", dial: "53", label: "Cuba", flag: "🇨🇺" },
  { code: "CW", dial: "599", label: "Curazao", flag: "🇨🇼" },
  { code: "DK", dial: "45", label: "Dinamarca", flag: "🇩🇰" },
  { code: "DM", dial: "1", label: "Dominica", flag: "🇩🇲" },
  { code: "EC", dial: "593", label: "Ecuador", flag: "🇪🇨" },
  { code: "EG", dial: "20", label: "Egipto", flag: "🇪🇬" },
  { code: "SV", dial: "503", label: "El Salvador", flag: "🇸🇻" },
  { code: "AE", dial: "971", label: "Emiratos Árabes Unidos", flag: "🇦🇪" },
  { code: "ER", dial: "291", label: "Eritrea", flag: "🇪🇷" },
  { code: "SK", dial: "421", label: "Eslovaquia", flag: "🇸🇰" },
  { code: "SI", dial: "386", label: "Eslovenia", flag: "🇸🇮" },
  { code: "ES", dial: "34", label: "España", flag: "🇪🇸" },
  { code: "US", dial: "1", label: "Estados Unidos", flag: "🇺🇸" },
  { code: "EE", dial: "372", label: "Estonia", flag: "🇪🇪" },
  { code: "SZ", dial: "268", label: "Esuatini", flag: "🇸🇿" },
  { code: "ET", dial: "251", label: "Etiopía", flag: "🇪🇹" },
  { code: "PH", dial: "63", label: "Filipinas", flag: "🇵🇭" },
  { code: "FI", dial: "358", label: "Finlandia", flag: "🇫🇮" },
  { code: "FJ", dial: "679", label: "Fiyi", flag: "🇫🇯" },
  { code: "FR", dial: "33", label: "Francia", flag: "🇫🇷" },
  { code: "GA", dial: "241", label: "Gabón", flag: "🇬🇦" },
  { code: "GM", dial: "220", label: "Gambia", flag: "🇬🇲" },
  { code: "GE", dial: "995", label: "Georgia", flag: "🇬🇪" },
  { code: "GH", dial: "233", label: "Ghana", flag: "🇬🇭" },
  { code: "GI", dial: "350", label: "Gibraltar", flag: "🇬🇮" },
  { code: "GD", dial: "1", label: "Granada", flag: "🇬🇩" },
  { code: "GR", dial: "30", label: "Grecia", flag: "🇬🇷" },
  { code: "GL", dial: "299", label: "Groenlandia", flag: "🇬🇱" },
  { code: "GT", dial: "502", label: "Guatemala", flag: "🇬🇹" },
  { code: "GG", dial: "44", label: "Guernesey", flag: "🇬🇬" },
  { code: "GN", dial: "224", label: "Guinea", flag: "🇬🇳" },
  { code: "GQ", dial: "240", label: "Guinea Ecuatorial", flag: "🇬🇶" },
  { code: "GW", dial: "245", label: "Guinea-Bisáu", flag: "🇬🇼" },
  { code: "GY", dial: "592", label: "Guyana", flag: "🇬🇾" },
  { code: "HT", dial: "509", label: "Haití", flag: "🇭🇹" },
  { code: "HN", dial: "504", label: "Honduras", flag: "🇭🇳" },
  { code: "HU", dial: "36", label: "Hungría", flag: "🇭🇺" },
  { code: "IN", dial: "91", label: "India", flag: "🇮🇳" },
  { code: "ID", dial: "62", label: "Indonesia", flag: "🇮🇩" },
  { code: "IQ", dial: "964", label: "Irak", flag: "🇮🇶" },
  { code: "IR", dial: "98", label: "Irán", flag: "🇮🇷" },
  { code: "IE", dial: "353", label: "Irlanda", flag: "🇮🇪" },
  { code: "IM", dial: "44", label: "Isla de Man", flag: "🇮🇲" },
  { code: "IS", dial: "354", label: "Islandia", flag: "🇮🇸" },
  { code: "FO", dial: "298", label: "Islas Feroe", flag: "🇫🇴" },
  { code: "MH", dial: "692", label: "Islas Marshall", flag: "🇲🇭" },
  { code: "SB", dial: "677", label: "Islas Salomón", flag: "🇸🇧" },
  { code: "IL", dial: "972", label: "Israel", flag: "🇮🇱" },
  { code: "IT", dial: "39", label: "Italia", flag: "🇮🇹" },
  { code: "JM", dial: "1", label: "Jamaica", flag: "🇯🇲" },
  { code: "JP", dial: "81", label: "Japón", flag: "🇯🇵" },
  { code: "JE", dial: "44", label: "Jersey", flag: "🇯🇪" },
  { code: "JO", dial: "962", label: "Jordania", flag: "🇯🇴" },
  { code: "KZ", dial: "7", label: "Kazajistán", flag: "🇰🇿" },
  { code: "KE", dial: "254", label: "Kenia", flag: "🇰🇪" },
  { code: "KG", dial: "996", label: "Kirguistán", flag: "🇰🇬" },
  { code: "KI", dial: "686", label: "Kiribati", flag: "🇰🇮" },
  { code: "XK", dial: "383", label: "Kosovo", flag: "🇽🇰" },
  { code: "KW", dial: "965", label: "Kuwait", flag: "🇰🇼" },
  { code: "LA", dial: "856", label: "Laos", flag: "🇱🇦" },
  { code: "LS", dial: "266", label: "Lesoto", flag: "🇱🇸" },
  { code: "LV", dial: "371", label: "Letonia", flag: "🇱🇻" },
  { code: "LB", dial: "961", label: "Líbano", flag: "🇱🇧" },
  { code: "LR", dial: "231", label: "Liberia", flag: "🇱🇷" },
  { code: "LY", dial: "218", label: "Libia", flag: "🇱🇾" },
  { code: "LI", dial: "423", label: "Liechtenstein", flag: "🇱🇮" },
  { code: "LT", dial: "370", label: "Lituania", flag: "🇱🇹" },
  { code: "LU", dial: "352", label: "Luxemburgo", flag: "🇱🇺" },
  { code: "MK", dial: "389", label: "Macedonia del Norte", flag: "🇲🇰" },
  { code: "MG", dial: "261", label: "Madagascar", flag: "🇲🇬" },
  { code: "MY", dial: "60", label: "Malasia", flag: "🇲🇾" },
  { code: "MW", dial: "265", label: "Malaui", flag: "🇲🇼" },
  { code: "MV", dial: "960", label: "Maldivas", flag: "🇲🇻" },
  { code: "ML", dial: "223", label: "Mali", flag: "🇲🇱" },
  { code: "MT", dial: "356", label: "Malta", flag: "🇲🇹" },
  { code: "MA", dial: "212", label: "Marruecos", flag: "🇲🇦" },
  { code: "MU", dial: "230", label: "Mauricio", flag: "🇲🇺" },
  { code: "MR", dial: "222", label: "Mauritania", flag: "🇲🇷" },
  { code: "MX", dial: "52", label: "México", flag: "🇲🇽" },
  { code: "FM", dial: "691", label: "Micronesia", flag: "🇫🇲" },
  { code: "MD", dial: "373", label: "Moldavia", flag: "🇲🇩" },
  { code: "MC", dial: "377", label: "Mónaco", flag: "🇲🇨" },
  { code: "MN", dial: "976", label: "Mongolia", flag: "🇲🇳" },
  { code: "ME", dial: "382", label: "Montenegro", flag: "🇲🇪" },
  { code: "MZ", dial: "258", label: "Mozambique", flag: "🇲🇿" },
  { code: "MM", dial: "95", label: "Myanmar (Birmania)", flag: "🇲🇲" },
  { code: "NA", dial: "264", label: "Namibia", flag: "🇳🇦" },
  { code: "NR", dial: "674", label: "Nauru", flag: "🇳🇷" },
  { code: "NP", dial: "977", label: "Nepal", flag: "🇳🇵" },
  { code: "NI", dial: "505", label: "Nicaragua", flag: "🇳🇮" },
  { code: "NE", dial: "227", label: "Níger", flag: "🇳🇪" },
  { code: "NG", dial: "234", label: "Nigeria", flag: "🇳🇬" },
  { code: "NO", dial: "47", label: "Noruega", flag: "🇳🇴" },
  { code: "NC", dial: "687", label: "Nueva Caledonia", flag: "🇳🇨" },
  { code: "NZ", dial: "64", label: "Nueva Zelanda", flag: "🇳🇿" },
  { code: "OM", dial: "968", label: "Omán", flag: "🇴🇲" },
  { code: "NL", dial: "31", label: "Países Bajos", flag: "🇳🇱" },
  { code: "PK", dial: "92", label: "Pakistán", flag: "🇵🇰" },
  { code: "PW", dial: "680", label: "Palaos", flag: "🇵🇼" },
  { code: "PA", dial: "507", label: "Panamá", flag: "🇵🇦" },
  { code: "PG", dial: "675", label: "Papúa Nueva Guinea", flag: "🇵🇬" },
  { code: "PY", dial: "595", label: "Paraguay", flag: "🇵🇾" },
  { code: "PE", dial: "51", label: "Perú", flag: "🇵🇪" },
  { code: "PF", dial: "689", label: "Polinesia Francesa", flag: "🇵🇫" },
  { code: "PL", dial: "48", label: "Polonia", flag: "🇵🇱" },
  { code: "PT", dial: "351", label: "Portugal", flag: "🇵🇹" },
  { code: "PR", dial: "1", label: "Puerto Rico", flag: "🇵🇷" },
  { code: "HK", dial: "852", label: "RAE de Hong Kong (China)", flag: "🇭🇰" },
  { code: "MO", dial: "853", label: "RAE de Macao (China)", flag: "🇲🇴" },
  { code: "GB", dial: "44", label: "Reino Unido", flag: "🇬🇧" },
  { code: "CF", dial: "236", label: "República Centroafricana", flag: "🇨🇫" },
  { code: "CD", dial: "243", label: "República Democrática del Congo", flag: "🇨🇩" },
  { code: "DO", dial: "1", label: "República Dominicana", flag: "🇩🇴" },
  { code: "RW", dial: "250", label: "Ruanda", flag: "🇷🇼" },
  { code: "RO", dial: "40", label: "Rumanía", flag: "🇷🇴" },
  { code: "RU", dial: "7", label: "Rusia", flag: "🇷🇺" },
  { code: "WS", dial: "685", label: "Samoa", flag: "🇼🇸" },
  { code: "KN", dial: "1", label: "San Cristóbal y Nieves", flag: "🇰🇳" },
  { code: "SM", dial: "378", label: "San Marino", flag: "🇸🇲" },
  { code: "VC", dial: "1", label: "San Vicente y las Granadinas", flag: "🇻🇨" },
  { code: "LC", dial: "1", label: "Santa Lucía", flag: "🇱🇨" },
  { code: "ST", dial: "239", label: "Santo Tomé y Príncipe", flag: "🇸🇹" },
  { code: "SN", dial: "221", label: "Senegal", flag: "🇸🇳" },
  { code: "RS", dial: "381", label: "Serbia", flag: "🇷🇸" },
  { code: "SC", dial: "248", label: "Seychelles", flag: "🇸🇨" },
  { code: "SL", dial: "232", label: "Sierra Leona", flag: "🇸🇱" },
  { code: "SG", dial: "65", label: "Singapur", flag: "🇸🇬" },
  { code: "SY", dial: "963", label: "Siria", flag: "🇸🇾" },
  { code: "SO", dial: "252", label: "Somalia", flag: "🇸🇴" },
  { code: "LK", dial: "94", label: "Sri Lanka", flag: "🇱🇰" },
  { code: "ZA", dial: "27", label: "Sudáfrica", flag: "🇿🇦" },
  { code: "SD", dial: "249", label: "Sudán", flag: "🇸🇩" },
  { code: "SS", dial: "211", label: "Sudán del Sur", flag: "🇸🇸" },
  { code: "SE", dial: "46", label: "Suecia", flag: "🇸🇪" },
  { code: "CH", dial: "41", label: "Suiza", flag: "🇨🇭" },
  { code: "SR", dial: "597", label: "Surinam", flag: "🇸🇷" },
  { code: "TH", dial: "66", label: "Tailandia", flag: "🇹🇭" },
  { code: "TW", dial: "886", label: "Taiwán", flag: "🇹🇼" },
  { code: "TZ", dial: "255", label: "Tanzania", flag: "🇹🇿" },
  { code: "TJ", dial: "992", label: "Tayikistán", flag: "🇹🇯" },
  { code: "PS", dial: "970", label: "Territorios Palestinos", flag: "🇵🇸" },
  { code: "TL", dial: "670", label: "Timor-Leste", flag: "🇹🇱" },
  { code: "TG", dial: "228", label: "Togo", flag: "🇹🇬" },
  { code: "TO", dial: "676", label: "Tonga", flag: "🇹🇴" },
  { code: "TT", dial: "1", label: "Trinidad y Tobago", flag: "🇹🇹" },
  { code: "TN", dial: "216", label: "Túnez", flag: "🇹🇳" },
  { code: "TM", dial: "993", label: "Turkmenistán", flag: "🇹🇲" },
  { code: "TR", dial: "90", label: "Turquía", flag: "🇹🇷" },
  { code: "TV", dial: "688", label: "Tuvalu", flag: "🇹🇻" },
  { code: "UA", dial: "380", label: "Ucrania", flag: "🇺🇦" },
  { code: "UG", dial: "256", label: "Uganda", flag: "🇺🇬" },
  { code: "UY", dial: "598", label: "Uruguay", flag: "🇺🇾" },
  { code: "UZ", dial: "998", label: "Uzbekistán", flag: "🇺🇿" },
  { code: "VU", dial: "678", label: "Vanuatu", flag: "🇻🇺" },
  { code: "VE", dial: "58", label: "Venezuela", flag: "🇻🇪" },
  { code: "VN", dial: "84", label: "Vietnam", flag: "🇻🇳" },
  { code: "YE", dial: "967", label: "Yemen", flag: "🇾🇪" },
  { code: "DJ", dial: "253", label: "Yibuti", flag: "🇩🇯" },
  { code: "ZM", dial: "260", label: "Zambia", flag: "🇿🇲" },
  { code: "ZW", dial: "263", label: "Zimbabue", flag: "🇿🇼" },
];

export const DEFAULT_COUNTRY = "PE";

// Dial codes ordenados por longitud desc → longest-match al parsear un E.164.
const BY_DIAL_LEN = [...COUNTRIES].sort((a, b) => b.dial.length - a.dial.length);

/** Deriva el país de un teléfono en E.164 ("+51..."). Ambiguos (+1) caen al
 *  primero de la lista; devuelve null si no hay match o el número es local. */
export const countryFromE164 = (phone: string | null | undefined): Country | null => {
  if (!phone) return null;
  const digits = phone.replace(/[^\d]/g, "");
  if (!phone.trim().startsWith("+") && digits.length <= 9) return null; // local sin país
  for (const c of BY_DIAL_LEN) {
    if (digits.startsWith(c.dial)) return c;
  }
  return null;
};

export const byCode = (code: string | null | undefined): Country | undefined =>
  COUNTRIES.find((c) => c.code === code);

/** Separa un teléfono en país + número nacional (sin el código de marcación).
 *  Para el selector: seedea desde un valor E.164 guardado. Si no reconoce país
 *  (número local viejo), country = null y national = los dígitos tal cual. */
export const parseE164 = (
  phone: string | null | undefined,
): { country: Country | null; national: string } => {
  const country = countryFromE164(phone);
  const digits = (phone ?? "").replace(/[^\d]/g, "");
  return { country, national: country ? digits.slice(country.dial.length) : digits };
};

