-- AUTOGENERADO por scratchpad/gen-countries.mjs — no editar a mano.
-- Catálogo de países para saber el origen de un teléfono/venta.
create table if not exists country (
  code      text primary key,          -- ISO 3166-1 alpha-2 (PE, CO)
  dial_code text not null,             -- código de marcación E.164 (51, 57)
  label     text not null,             -- nombre en español
  flag      text not null              -- bandera emoji
);

insert into country (code, dial_code, label, flag) values
  ('AF', '93', 'Afganistán', '🇦🇫'),
  ('AL', '355', 'Albania', '🇦🇱'),
  ('DE', '49', 'Alemania', '🇩🇪'),
  ('AD', '376', 'Andorra', '🇦🇩'),
  ('AO', '244', 'Angola', '🇦🇴'),
  ('AG', '1', 'Antigua y Barbuda', '🇦🇬'),
  ('SA', '966', 'Arabia Saudí', '🇸🇦'),
  ('DZ', '213', 'Argelia', '🇩🇿'),
  ('AR', '54', 'Argentina', '🇦🇷'),
  ('AM', '374', 'Armenia', '🇦🇲'),
  ('AW', '297', 'Aruba', '🇦🇼'),
  ('AU', '61', 'Australia', '🇦🇺'),
  ('AT', '43', 'Austria', '🇦🇹'),
  ('AZ', '994', 'Azerbaiyán', '🇦🇿'),
  ('BS', '1', 'Bahamas', '🇧🇸'),
  ('BD', '880', 'Bangladés', '🇧🇩'),
  ('BB', '1', 'Barbados', '🇧🇧'),
  ('BH', '973', 'Baréin', '🇧🇭'),
  ('BE', '32', 'Bélgica', '🇧🇪'),
  ('BZ', '501', 'Belice', '🇧🇿'),
  ('BJ', '229', 'Benín', '🇧🇯'),
  ('BY', '375', 'Bielorrusia', '🇧🇾'),
  ('BO', '591', 'Bolivia', '🇧🇴'),
  ('BA', '387', 'Bosnia y Herzegovina', '🇧🇦'),
  ('BW', '267', 'Botsuana', '🇧🇼'),
  ('BR', '55', 'Brasil', '🇧🇷'),
  ('BN', '673', 'Brunéi', '🇧🇳'),
  ('BG', '359', 'Bulgaria', '🇧🇬'),
  ('BF', '226', 'Burkina Faso', '🇧🇫'),
  ('BI', '257', 'Burundi', '🇧🇮'),
  ('BT', '975', 'Bután', '🇧🇹'),
  ('CV', '238', 'Cabo Verde', '🇨🇻'),
  ('KH', '855', 'Camboya', '🇰🇭'),
  ('CM', '237', 'Camerún', '🇨🇲'),
  ('CA', '1', 'Canadá', '🇨🇦'),
  ('QA', '974', 'Catar', '🇶🇦'),
  ('TD', '235', 'Chad', '🇹🇩'),
  ('CZ', '420', 'Chequia', '🇨🇿'),
  ('CL', '56', 'Chile', '🇨🇱'),
  ('CN', '86', 'China', '🇨🇳'),
  ('CY', '357', 'Chipre', '🇨🇾'),
  ('VA', '379', 'Ciudad del Vaticano', '🇻🇦'),
  ('CO', '57', 'Colombia', '🇨🇴'),
  ('KM', '269', 'Comoras', '🇰🇲'),
  ('CG', '242', 'Congo', '🇨🇬'),
  ('KP', '850', 'Corea del Norte', '🇰🇵'),
  ('KR', '82', 'Corea del Sur', '🇰🇷'),
  ('CR', '506', 'Costa Rica', '🇨🇷'),
  ('CI', '225', 'Côte d’Ivoire', '🇨🇮'),
  ('HR', '385', 'Croacia', '🇭🇷'),
  ('CU', '53', 'Cuba', '🇨🇺'),
  ('CW', '599', 'Curazao', '🇨🇼'),
  ('DK', '45', 'Dinamarca', '🇩🇰'),
  ('DM', '1', 'Dominica', '🇩🇲'),
  ('EC', '593', 'Ecuador', '🇪🇨'),
  ('EG', '20', 'Egipto', '🇪🇬'),
  ('SV', '503', 'El Salvador', '🇸🇻'),
  ('AE', '971', 'Emiratos Árabes Unidos', '🇦🇪'),
  ('ER', '291', 'Eritrea', '🇪🇷'),
  ('SK', '421', 'Eslovaquia', '🇸🇰'),
  ('SI', '386', 'Eslovenia', '🇸🇮'),
  ('ES', '34', 'España', '🇪🇸'),
  ('US', '1', 'Estados Unidos', '🇺🇸'),
  ('EE', '372', 'Estonia', '🇪🇪'),
  ('SZ', '268', 'Esuatini', '🇸🇿'),
  ('ET', '251', 'Etiopía', '🇪🇹'),
  ('PH', '63', 'Filipinas', '🇵🇭'),
  ('FI', '358', 'Finlandia', '🇫🇮'),
  ('FJ', '679', 'Fiyi', '🇫🇯'),
  ('FR', '33', 'Francia', '🇫🇷'),
  ('GA', '241', 'Gabón', '🇬🇦'),
  ('GM', '220', 'Gambia', '🇬🇲'),
  ('GE', '995', 'Georgia', '🇬🇪'),
  ('GH', '233', 'Ghana', '🇬🇭'),
  ('GI', '350', 'Gibraltar', '🇬🇮'),
  ('GD', '1', 'Granada', '🇬🇩'),
  ('GR', '30', 'Grecia', '🇬🇷'),
  ('GL', '299', 'Groenlandia', '🇬🇱'),
  ('GT', '502', 'Guatemala', '🇬🇹'),
  ('GG', '44', 'Guernesey', '🇬🇬'),
  ('GN', '224', 'Guinea', '🇬🇳'),
  ('GQ', '240', 'Guinea Ecuatorial', '🇬🇶'),
  ('GW', '245', 'Guinea-Bisáu', '🇬🇼'),
  ('GY', '592', 'Guyana', '🇬🇾'),
  ('HT', '509', 'Haití', '🇭🇹'),
  ('HN', '504', 'Honduras', '🇭🇳'),
  ('HU', '36', 'Hungría', '🇭🇺'),
  ('IN', '91', 'India', '🇮🇳'),
  ('ID', '62', 'Indonesia', '🇮🇩'),
  ('IQ', '964', 'Irak', '🇮🇶'),
  ('IR', '98', 'Irán', '🇮🇷'),
  ('IE', '353', 'Irlanda', '🇮🇪'),
  ('IM', '44', 'Isla de Man', '🇮🇲'),
  ('IS', '354', 'Islandia', '🇮🇸'),
  ('FO', '298', 'Islas Feroe', '🇫🇴'),
  ('MH', '692', 'Islas Marshall', '🇲🇭'),
  ('SB', '677', 'Islas Salomón', '🇸🇧'),
  ('IL', '972', 'Israel', '🇮🇱'),
  ('IT', '39', 'Italia', '🇮🇹'),
  ('JM', '1', 'Jamaica', '🇯🇲'),
  ('JP', '81', 'Japón', '🇯🇵'),
  ('JE', '44', 'Jersey', '🇯🇪'),
  ('JO', '962', 'Jordania', '🇯🇴'),
  ('KZ', '7', 'Kazajistán', '🇰🇿'),
  ('KE', '254', 'Kenia', '🇰🇪'),
  ('KG', '996', 'Kirguistán', '🇰🇬'),
  ('KI', '686', 'Kiribati', '🇰🇮'),
  ('XK', '383', 'Kosovo', '🇽🇰'),
  ('KW', '965', 'Kuwait', '🇰🇼'),
  ('LA', '856', 'Laos', '🇱🇦'),
  ('LS', '266', 'Lesoto', '🇱🇸'),
  ('LV', '371', 'Letonia', '🇱🇻'),
  ('LB', '961', 'Líbano', '🇱🇧'),
  ('LR', '231', 'Liberia', '🇱🇷'),
  ('LY', '218', 'Libia', '🇱🇾'),
  ('LI', '423', 'Liechtenstein', '🇱🇮'),
  ('LT', '370', 'Lituania', '🇱🇹'),
  ('LU', '352', 'Luxemburgo', '🇱🇺'),
  ('MK', '389', 'Macedonia del Norte', '🇲🇰'),
  ('MG', '261', 'Madagascar', '🇲🇬'),
  ('MY', '60', 'Malasia', '🇲🇾'),
  ('MW', '265', 'Malaui', '🇲🇼'),
  ('MV', '960', 'Maldivas', '🇲🇻'),
  ('ML', '223', 'Mali', '🇲🇱'),
  ('MT', '356', 'Malta', '🇲🇹'),
  ('MA', '212', 'Marruecos', '🇲🇦'),
  ('MU', '230', 'Mauricio', '🇲🇺'),
  ('MR', '222', 'Mauritania', '🇲🇷'),
  ('MX', '52', 'México', '🇲🇽'),
  ('FM', '691', 'Micronesia', '🇫🇲'),
  ('MD', '373', 'Moldavia', '🇲🇩'),
  ('MC', '377', 'Mónaco', '🇲🇨'),
  ('MN', '976', 'Mongolia', '🇲🇳'),
  ('ME', '382', 'Montenegro', '🇲🇪'),
  ('MZ', '258', 'Mozambique', '🇲🇿'),
  ('MM', '95', 'Myanmar (Birmania)', '🇲🇲'),
  ('NA', '264', 'Namibia', '🇳🇦'),
  ('NR', '674', 'Nauru', '🇳🇷'),
  ('NP', '977', 'Nepal', '🇳🇵'),
  ('NI', '505', 'Nicaragua', '🇳🇮'),
  ('NE', '227', 'Níger', '🇳🇪'),
  ('NG', '234', 'Nigeria', '🇳🇬'),
  ('NO', '47', 'Noruega', '🇳🇴'),
  ('NC', '687', 'Nueva Caledonia', '🇳🇨'),
  ('NZ', '64', 'Nueva Zelanda', '🇳🇿'),
  ('OM', '968', 'Omán', '🇴🇲'),
  ('NL', '31', 'Países Bajos', '🇳🇱'),
  ('PK', '92', 'Pakistán', '🇵🇰'),
  ('PW', '680', 'Palaos', '🇵🇼'),
  ('PA', '507', 'Panamá', '🇵🇦'),
  ('PG', '675', 'Papúa Nueva Guinea', '🇵🇬'),
  ('PY', '595', 'Paraguay', '🇵🇾'),
  ('PE', '51', 'Perú', '🇵🇪'),
  ('PF', '689', 'Polinesia Francesa', '🇵🇫'),
  ('PL', '48', 'Polonia', '🇵🇱'),
  ('PT', '351', 'Portugal', '🇵🇹'),
  ('PR', '1', 'Puerto Rico', '🇵🇷'),
  ('HK', '852', 'RAE de Hong Kong (China)', '🇭🇰'),
  ('MO', '853', 'RAE de Macao (China)', '🇲🇴'),
  ('GB', '44', 'Reino Unido', '🇬🇧'),
  ('CF', '236', 'República Centroafricana', '🇨🇫'),
  ('CD', '243', 'República Democrática del Congo', '🇨🇩'),
  ('DO', '1', 'República Dominicana', '🇩🇴'),
  ('RW', '250', 'Ruanda', '🇷🇼'),
  ('RO', '40', 'Rumanía', '🇷🇴'),
  ('RU', '7', 'Rusia', '🇷🇺'),
  ('WS', '685', 'Samoa', '🇼🇸'),
  ('KN', '1', 'San Cristóbal y Nieves', '🇰🇳'),
  ('SM', '378', 'San Marino', '🇸🇲'),
  ('VC', '1', 'San Vicente y las Granadinas', '🇻🇨'),
  ('LC', '1', 'Santa Lucía', '🇱🇨'),
  ('ST', '239', 'Santo Tomé y Príncipe', '🇸🇹'),
  ('SN', '221', 'Senegal', '🇸🇳'),
  ('RS', '381', 'Serbia', '🇷🇸'),
  ('SC', '248', 'Seychelles', '🇸🇨'),
  ('SL', '232', 'Sierra Leona', '🇸🇱'),
  ('SG', '65', 'Singapur', '🇸🇬'),
  ('SY', '963', 'Siria', '🇸🇾'),
  ('SO', '252', 'Somalia', '🇸🇴'),
  ('LK', '94', 'Sri Lanka', '🇱🇰'),
  ('ZA', '27', 'Sudáfrica', '🇿🇦'),
  ('SD', '249', 'Sudán', '🇸🇩'),
  ('SS', '211', 'Sudán del Sur', '🇸🇸'),
  ('SE', '46', 'Suecia', '🇸🇪'),
  ('CH', '41', 'Suiza', '🇨🇭'),
  ('SR', '597', 'Surinam', '🇸🇷'),
  ('TH', '66', 'Tailandia', '🇹🇭'),
  ('TW', '886', 'Taiwán', '🇹🇼'),
  ('TZ', '255', 'Tanzania', '🇹🇿'),
  ('TJ', '992', 'Tayikistán', '🇹🇯'),
  ('PS', '970', 'Territorios Palestinos', '🇵🇸'),
  ('TL', '670', 'Timor-Leste', '🇹🇱'),
  ('TG', '228', 'Togo', '🇹🇬'),
  ('TO', '676', 'Tonga', '🇹🇴'),
  ('TT', '1', 'Trinidad y Tobago', '🇹🇹'),
  ('TN', '216', 'Túnez', '🇹🇳'),
  ('TM', '993', 'Turkmenistán', '🇹🇲'),
  ('TR', '90', 'Turquía', '🇹🇷'),
  ('TV', '688', 'Tuvalu', '🇹🇻'),
  ('UA', '380', 'Ucrania', '🇺🇦'),
  ('UG', '256', 'Uganda', '🇺🇬'),
  ('UY', '598', 'Uruguay', '🇺🇾'),
  ('UZ', '998', 'Uzbekistán', '🇺🇿'),
  ('VU', '678', 'Vanuatu', '🇻🇺'),
  ('VE', '58', 'Venezuela', '🇻🇪'),
  ('VN', '84', 'Vietnam', '🇻🇳'),
  ('YE', '967', 'Yemen', '🇾🇪'),
  ('DJ', '253', 'Yibuti', '🇩🇯'),
  ('ZM', '260', 'Zambia', '🇿🇲'),
  ('ZW', '263', 'Zimbabue', '🇿🇼')
on conflict (code) do update
  set dial_code = excluded.dial_code, label = excluded.label, flag = excluded.flag;

-- Solo lectura para el resto (catálogo público).
alter table country enable row level security;
drop policy if exists country_read on country;
create policy country_read on country for select using (true);
grant select on country to anon, authenticated;
